### ISSUE TITLE
Unable to parse expiration time from fflood statment file

### ISSUE THREAD

**Issue by quintusdias** [quintusdias/jgenowcoast#28]
```
Traceback (most recent call last):
  File "tests/test_all.py", line 170, in test_fflood2_statment
    hzf = HazardsFile(path)
  File "hazards/hazards.py", line 309, in __init__
    bltn = Bulletin(text_item, file_base_date)
  File "hazards/hazards.py", line 395, in __init__
    self.parse_universal_geographic_code()
  File "hazards/hazards.py", line 462, in parse_universal_geographic_code
    raise RuntimeError("Could not parse expiration time.")
RuntimeError: Could not parse expiration time.
```

**Comment by quintusdias** [comment]
Here is the entire segment.  Already this violates the standard, as '$$' should be flush against the left hand side, not indented.

```
$$^M                                                                            
^M                                                                              
DL^M                                                                            
^M                                                                              
^C^A^M                                                                          
999 ^M                                                                          
FGUS82 KMFL 240058^M                                                            
RVSMFL^M                                                                        
Hydrologic Statement^M                                                          
National Weather Service Miami FL^M                                             
858 PM EDT THU JUL 23 2015^M                                                    
^M                                                                              
 $$^M                                                                           
             Fld  Observed          Forecast 7AM     ^M                         
Location     STG  Stg  Day Time     Fri    Sat    Sun^M                         
^M                                                                              
Lake Okeechobee/Fisheating Creek^M                                              
  Palmdale     7   5.2 Thu 08 PM    5.4    5.3    5.2^M
^M                                                                              
Stay tuned to NOAA Weather Radio for additional information and updates.^M      
^M                                                                              
^C   
```

**Comment by quintusdias** [comment]
Files in `/common/data/observations/noaaport/nwx/fflood/obs` constitute another such case.

Something in common may be lines reading `MISCELLANEOUS HYDROLOGIC REPORT`???

**Comment by quintusdias** [comment]
Also for `/common/data/observations/noaaport/nwx/watch_warn/state_summ`
