### ISSUE TITLE
Error parsing a wcn file

### ISSUE THREAD

**Issue by quintusdias** [quintusdias/jgenowcoast#34]
```
2015032514.wcn
Traceback (most recent call last):
  File "/usr1/jevans/.local/bin/hzparse", line 9, in <module>
    load_entry_point('hazards==0.0.1', 'console_scripts', 'hzparse')()
  File "/usr1/jevans/git/jgenowcoast/hazards/command_line.py", line 33, in hzparse
    hzf = HazardsFile(os.path.join(args.directory, file))
  File "/usr1/jevans/git/jgenowcoast/hazards/hazards.py", line 360, in __init__
    prod = Product(text_item, base_date=file_base_date)
  File "/usr1/jevans/git/jgenowcoast/hazards/hazards.py", line 430, in __init__
    self.parse_wmo_abbreviated_heading_awips_id()
  File "/usr1/jevans/git/jgenowcoast/hazards/hazards.py", line 458, in parse_wmo_abbreviated_heading_awips_id
    raise InvalidProductException()
hazards.hazards.InvalidProductException
```

**Comment by quintusdias** [comment]
A test message is what is causing it

```
^M
$$^M
^M
THIS IS A TEST MESSAGE. DO NOT TAKE ACTION BASED ON THIS TEST^M
MESSAGE.^M
^M
$$^M
```

**Comment by quintusdias** [comment]
According to the spec, the text "THIS IS A TEST MESSAGE" must be in the free text body.

**Comment by quintusdias** [comment]
:
